"""initial schema

Revision ID: 923da4aa4e08
Revises: 
Create Date: 2026-08-27 04:33:04.415870
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '923da4aa4e08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_metric_mappings',
    sa.Column('adapter_key', sa.String(length=128), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=False),
    sa.Column('firmware_range', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=256), nullable=False),
    sa.Column('canonical_metric_key', sa.String(length=128), nullable=False),
    sa.Column('dimension_value', sa.String(length=32), nullable=False),
    sa.Column('source_unit', sa.String(length=32), nullable=True),
    sa.Column('target_unit', sa.String(length=32), nullable=True),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.Column('transform_expression', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adapter_metric_mappings')),
    sa.UniqueConstraint('adapter_key', 'adapter_version', 'firmware_range', 'canonical_metric_key', 'dimension_value', name=op.f('uq_adapter_metric_mappings_adapter_key_adapter_version_firmware_range_canonical_metric_key_dimension_value'))
    )
    with op.batch_alter_table('adapter_metric_mappings', schema=None) as batch_op:
        batch_op.create_index('ix_adapter_metric_mappings_lookup', ['adapter_key', 'adapter_version'], unique=False)

    op.create_table('collection_profiles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('data_check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('connect_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('request_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_profiles')),
    sa.UniqueConstraint('name', name=op.f('uq_collection_profiles_name'))
    )
    op.create_table('manufacturers',
    sa.Column('manufacturer_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers')),
    sa.UniqueConstraint('manufacturer_code', name=op.f('uq_manufacturers_manufacturer_code'))
    )
    op.create_table('metric_definitions',
    sa.Column('metric_key', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('measurement', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('aggregation', sa.String(length=16), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('capability_key', sa.String(length=128), nullable=True),
    sa.Column('catalog_version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('metric_key', name=op.f('pk_metric_definitions'))
    )
    op.create_table('metric_profiles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_profiles')),
    sa.UniqueConstraint('name', name=op.f('uq_metric_profiles_name'))
    )
    op.create_table('regions',
    sa.Column('region_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('region_code', name=op.f('uq_regions_region_code'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('adapter_definitions',
    sa.Column('adapter_key', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('current_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('configuration_schema', sa.JSON(), nullable=False),
    sa.Column('ui_schema', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_adapter_definitions_manufacturer_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('adapter_key', name=op.f('pk_adapter_definitions'))
    )
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_occurred_at', ['occurred_at'], unique=False)

    op.create_table('device_models',
    sa.Column('manufacturer_id', sa.Uuid(), nullable=False),
    sa.Column('model_code', sa.String(length=64), nullable=False),
    sa.Column('product_family', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.String(length=32), nullable=True),
    sa.Column('default_adapter_key', sa.String(length=128), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=True),
    sa.Column('sensor_port_count', sa.Integer(), nullable=True),
    sa.Column('external_soh_channels', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_device_models_manufacturer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_models')),
    sa.UniqueConstraint('manufacturer_id', 'model_code', name=op.f('uq_device_models_manufacturer_id_model_code'))
    )
    op.create_table('edge_collectors',
    sa.Column('edge_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ENROLLING', 'ONLINE', 'DEGRADED', 'OFFLINE', 'DISABLED', name='edge_status', native_enum=False, length=32), nullable=False),
    sa.Column('software_version', sa.String(length=32), nullable=True),
    sa.Column('installed_adapters', sa.JSON(), nullable=False),
    sa.Column('certificate_serial', sa.String(length=128), nullable=True),
    sa.Column('certificate_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrollment_token_hash', sa.String(length=128), nullable=True),
    sa.Column('enrollment_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_upload_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_config_version', sa.Integer(), nullable=False),
    sa.Column('last_config_applied_version', sa.Integer(), nullable=False),
    sa.Column('last_config_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spool_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('spool_limit_bytes', sa.BigInteger(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_edge_collectors_region_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge_collectors')),
    sa.UniqueConstraint('edge_code', name=op.f('uq_edge_collectors_edge_code'))
    )
    op.create_table('maintenance_windows',
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('suppress_alerts', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_maintenance_windows_created_by'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_windows'))
    )
    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.create_index('ix_maintenance_windows_period', ['starts_at', 'ends_at'], unique=False)

    op.create_table('profile_metrics',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('alerting_enabled', sa.Boolean(), nullable=False),
    sa.Column('warning_condition', sa.JSON(), nullable=False),
    sa.Column('critical_condition', sa.JSON(), nullable=False),
    sa.Column('hold_seconds', sa.Integer(), nullable=False),
    sa.Column('recovery_seconds', sa.Integer(), nullable=False),
    sa.Column('consecutive_violations', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_definitions.metric_key'], name=op.f('fk_profile_metrics_metric_key'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['metric_profiles.id'], name=op.f('fk_profile_metrics_profile_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_metrics')),
    sa.UniqueConstraint('profile_id', 'metric_key', name=op.f('uq_profile_metrics_profile_id_metric_key'))
    )
    op.create_table('stations',
    sa.Column('station_code', sa.String(length=16), nullable=False),
    sa.Column('network_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('operator_name', sa.String(length=64), nullable=True),
    sa.Column('operator_contact', sa.String(length=128), nullable=True),
    sa.Column('power_profile', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'SUSPENDED', 'RETIRED', name='lifecycle_status', native_enum=False, length=32), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_stations_region_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations')),
    sa.UniqueConstraint('network_code', 'station_code', name=op.f('uq_stations_network_code_station_code'))
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index('ix_stations_status', ['status'], unique=False)

    op.create_table('adapter_versions',
    sa.Column('adapter_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('minimum_collector_version', sa.String(length=32), nullable=True),
    sa.Column('minimum_edge_version', sa.String(length=32), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['adapter_key'], ['adapter_definitions.adapter_key'], name=op.f('fk_adapter_versions_adapter_key'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adapter_versions')),
    sa.UniqueConstraint('adapter_key', 'version', name=op.f('uq_adapter_versions_adapter_key_version'))
    )
    op.create_table('devices',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('device_model_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('instrument_id', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('adapter_key', sa.String(length=128), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('collection_mode', sa.Enum('DIRECT', 'EDGE', name='collection_mode', native_enum=False, length=32), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=True),
    sa.Column('collection_profile_id', sa.Uuid(), nullable=True),
    sa.Column('metric_profile_id', sa.Uuid(), nullable=True),
    sa.Column('data_source_uri', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'SUSPENDED', 'RETIRED', name='lifecycle_status', native_enum=False, length=32), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("collection_mode <> 'EDGE' OR edge_id IS NOT NULL", name=op.f('ck_devices_edge_mode_requires_edge')),
    sa.ForeignKeyConstraint(['collection_profile_id'], ['collection_profiles.id'], name=op.f('fk_devices_collection_profile_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_models.id'], name=op.f('fk_devices_device_model_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_collectors.id'], name=op.f('fk_devices_edge_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_devices_manufacturer_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_profile_id'], ['metric_profiles.id'], name=op.f('fk_devices_metric_profile_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_devices_station_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ix_devices_collection_mode', ['collection_mode'], unique=False)
        batch_op.create_index('ix_devices_next_poll_at', ['next_poll_at'], unique=False)

    op.create_table('edge_ingest_batches',
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('first_sequence', sa.BigInteger(), nullable=False),
    sa.Column('last_sequence', sa.BigInteger(), nullable=False),
    sa.Column('poll_count', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSED', 'DUPLICATE', 'REJECTED', name='batch_status', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_collectors.id'], name=op.f('fk_edge_ingest_batches_edge_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge_ingest_batches')),
    sa.UniqueConstraint('edge_id', 'batch_id', name=op.f('uq_edge_ingest_batches_edge_id_batch_id'))
    )
    with op.batch_alter_table('edge_ingest_batches', schema=None) as batch_op:
        batch_op.create_index('ix_edge_ingest_batches_received_at', ['received_at'], unique=False)

    op.create_table('edge_runtime_states',
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('connectivity_status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('config_status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('collector_status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('spool_status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('certificate_status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('clock_status', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('pending_batches', sa.Integer(), nullable=True),
    sa.Column('oldest_pending_age_seconds', sa.Float(), nullable=True),
    sa.Column('clock_offset_ms', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_collectors.id'], name=op.f('fk_edge_runtime_states_edge_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edge_id', name=op.f('pk_edge_runtime_states'))
    )
    op.create_table('device_capabilities',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('capability_key', sa.String(length=128), nullable=False),
    sa.Column('dimension_value', sa.String(length=32), nullable=False),
    sa.Column('support_state', sa.Enum('SUPPORTED_ENABLED', 'SUPPORTED_DISABLED', 'UNSUPPORTED', 'UNKNOWN', 'ERROR', name='support_state', native_enum=False, length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_capabilities_device_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_capabilities')),
    sa.UniqueConstraint('device_id', 'capability_key', 'dimension_value', name=op.f('uq_device_capabilities_device_id_capability_key_dimension_value'))
    )
    op.create_table('device_endpoints',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sa.String(length=8), nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('base_path', sa.String(length=128), nullable=False),
    sa.Column('tls_verify', sa.Boolean(), nullable=False),
    sa.Column('credential_reference', sa.String(length=256), nullable=True),
    sa.Column('connect_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('request_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('connection_options', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_endpoints_device_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_endpoints')),
    sa.UniqueConstraint('device_id', name=op.f('uq_device_endpoints_device_id'))
    )
    op.create_table('device_metric_overrides',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('metric_key', sa.String(length=128), nullable=False),
    sa.Column('dimension_value', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('alerting_enabled', sa.Boolean(), nullable=True),
    sa.Column('warning_condition', sa.JSON(), nullable=True),
    sa.Column('critical_condition', sa.JSON(), nullable=True),
    sa.Column('hold_seconds', sa.Integer(), nullable=True),
    sa.Column('recovery_seconds', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_metric_overrides_device_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_key'], ['metric_definitions.metric_key'], name=op.f('fk_device_metric_overrides_metric_key'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_metric_overrides')),
    sa.UniqueConstraint('device_id', 'metric_key', 'dimension_value', name=op.f('uq_device_metric_overrides_device_id_metric_key_dimension_value'))
    )
    op.create_table('device_runtime_states',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.Enum('DNS_FAILURE', 'CONNECTION_REFUSED', 'CONNECT_TIMEOUT', 'REQUEST_TIMEOUT', 'TLS_ERROR', 'HTTP_ERROR', 'AUTH_ERROR', 'INVALID_PAYLOAD', 'IDENTITY_MISMATCH', 'ADAPTER_ERROR', 'STORAGE_ERROR', 'UNKNOWN', name='poll_error_code', native_enum=False, length=32), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('overall_severity', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('poll_lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_lease_owner', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_runtime_states_device_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_device_runtime_states'))
    )
    op.create_table('edge_assignments',
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_epoch', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_edge_assignments_device_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_collectors.id'], name=op.f('fk_edge_assignments_edge_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge_assignments')),
    sa.UniqueConstraint('edge_id', 'device_id', 'assignment_epoch', name=op.f('uq_edge_assignments_edge_id_device_id_assignment_epoch'))
    )
    with op.batch_alter_table('edge_assignments', schema=None) as batch_op:
        batch_op.create_index('uq_edge_assignments_active_device', ['device_id'], unique=True, postgresql_where=sa.text('enabled'), sqlite_where=sa.text('enabled = 1'))

    op.create_table('external_soh_channels',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('channel_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('measurement_type', sa.String(length=32), nullable=False),
    sa.Column('raw_unit', sa.String(length=16), nullable=False),
    sa.Column('output_unit', sa.String(length=16), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.Column('warning_low', sa.Float(), nullable=True),
    sa.Column('warning_high', sa.Float(), nullable=True),
    sa.Column('critical_low', sa.Float(), nullable=True),
    sa.Column('critical_high', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_external_soh_channels_device_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_soh_channels')),
    sa.UniqueConstraint('device_id', 'channel_number', name=op.f('uq_external_soh_channels_device_id_channel_number'))
    )
    op.create_table('health_states',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('dimension_value', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('support_state', sa.Enum('SUPPORTED_ENABLED', 'SUPPORTED_DISABLED', 'UNSUPPORTED', 'UNKNOWN', 'ERROR', name='support_state', native_enum=False, length=32), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_text', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_health_states_device_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_states')),
    sa.UniqueConstraint('device_id', 'category', 'dimension_value', name=op.f('uq_health_states_device_id_category_dimension_value'))
    )
    op.create_table('incidents',
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('edge_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('metric_key', sa.String(length=128), nullable=True),
    sa.Column('dimension_value', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.Enum('OK', 'WARNING', 'CRITICAL', 'UNKNOWN', 'DISABLED', 'MAINTENANCE', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='incident_status', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('worst_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('suppressed_by_edge', sa.Boolean(), nullable=False),
    sa.Column('maintenance_related', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_incidents_acknowledged_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_incidents_device_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_collectors.id'], name=op.f('fk_incidents_edge_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_incidents_station_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_device_status', ['device_id', 'status'], unique=False)
        batch_op.create_index('ix_incidents_status', ['status'], unique=False)

    op.create_table('poll_runs',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=True),
    sa.Column('poll_id', sa.String(length=64), nullable=False),
    sa.Column('collection_mode', sa.Enum('DIRECT', 'EDGE', name='collection_mode', native_enum=False, length=32), nullable=False),
    sa.Column('adapter_key', sa.String(length=128), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('payload_bytes', sa.Integer(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.Enum('DNS_FAILURE', 'CONNECTION_REFUSED', 'CONNECT_TIMEOUT', 'REQUEST_TIMEOUT', 'TLS_ERROR', 'HTTP_ERROR', 'AUTH_ERROR', 'INVALID_PAYLOAD', 'IDENTITY_MISMATCH', 'ADAPTER_ERROR', 'STORAGE_ERROR', 'UNKNOWN', name='poll_error_code', native_enum=False, length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('unmapped_values', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_poll_runs_device_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edge_id'], ['edge_collectors.id'], name=op.f('fk_poll_runs_edge_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll_runs')),
    sa.UniqueConstraint('poll_id', name=op.f('uq_poll_runs_poll_id'))
    )
    with op.batch_alter_table('poll_runs', schema=None) as batch_op:
        batch_op.create_index('ix_poll_runs_device_observed', ['device_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_poll_runs_observed_at', ['observed_at'], unique=False)

    op.create_table('sensors',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('port', sa.String(length=8), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('axis_count', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sensors_device_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors')),
    sa.UniqueConstraint('device_id', 'port', name=op.f('uq_sensors_device_id_port'))
    )
    op.create_table('incident_events',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='incident_status', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='incident_status', native_enum=False, length=32), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_incident_events_actor_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events'))
    )
    op.create_table('sensor_axes',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('axis_code', sa.String(length=8), nullable=False),
    sa.Column('soh_channel', sa.String(length=32), nullable=True),
    sa.Column('warning_threshold', sa.Float(), nullable=True),
    sa.Column('critical_threshold', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_sensor_axes_sensor_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_axes')),
    sa.UniqueConstraint('sensor_id', 'axis_code', name=op.f('uq_sensor_axes_sensor_id_axis_code'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_axes')
    op.drop_table('incident_events')
    op.drop_table('sensors')
    with op.batch_alter_table('poll_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_poll_runs_observed_at')
        batch_op.drop_index('ix_poll_runs_device_observed')

    op.drop_table('poll_runs')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_status')
        batch_op.drop_index('ix_incidents_device_status')

    op.drop_table('incidents')
    op.drop_table('health_states')
    op.drop_table('external_soh_channels')
    with op.batch_alter_table('edge_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_edge_assignments_active_device', postgresql_where=sa.text('enabled'), sqlite_where=sa.text('enabled = 1'))

    op.drop_table('edge_assignments')
    op.drop_table('device_runtime_states')
    op.drop_table('device_metric_overrides')
    op.drop_table('device_endpoints')
    op.drop_table('device_capabilities')
    op.drop_table('edge_runtime_states')
    with op.batch_alter_table('edge_ingest_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_edge_ingest_batches_received_at')

    op.drop_table('edge_ingest_batches')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ix_devices_next_poll_at')
        batch_op.drop_index('ix_devices_collection_mode')

    op.drop_table('devices')
    op.drop_table('adapter_versions')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index('ix_stations_status')

    op.drop_table('stations')
    op.drop_table('profile_metrics')
    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.drop_index('ix_maintenance_windows_period')

    op.drop_table('maintenance_windows')
    op.drop_table('edge_collectors')
    op.drop_table('device_models')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_occurred_at')

    op.drop_table('audit_logs')
    op.drop_table('adapter_definitions')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('metric_profiles')
    op.drop_table('metric_definitions')
    op.drop_table('manufacturers')
    op.drop_table('collection_profiles')
    with op.batch_alter_table('adapter_metric_mappings', schema=None) as batch_op:
        batch_op.drop_index('ix_adapter_metric_mappings_lookup')

    op.drop_table('adapter_metric_mappings')
    # ### end Alembic commands ###
